Repository microsoft/FLAML, pull requests merged in 2023-05, with the labels that each got.

#1009 fix NLP zero division error
  flaml/automl/model.py
  flaml/automl/nlp/huggingface/utils.py
Labels: bug

#1025 Human agent
  flaml/autogen/agent/agent.py
  flaml/autogen/agent/chat_agent.py
  flaml/autogen/agent/coding_agent.py
  flaml/autogen/agent/execution_agent.py
  flaml/autogen/agent/human_proxy_agent.py
  test/autogen/test_agent.py
  test/autogen/test_human_proxy_agent.py
Labels: enhancement

#1026 Blogpost
  website/blog/2023-05-07-1M-milestone/index.mdx
  website/blog/authors.yml
Labels: communication

#1039 response filter
  .github/workflows/openai.yml
  flaml/autogen/agent/agent.py
  flaml/autogen/agent/user_proxy_agent.py
  flaml/autogen/code_utils.py
  flaml/autogen/math_utils.py
  flaml/autogen/oai/__init__.py
  flaml/autogen/oai/completion.py
  flaml/autogen/oai/openai_utils.py
  flaml/tune/space.py
  notebook/autogen_chatgpt.ipynb
  notebook/autogen_chatgpt_gpt4.ipynb
  notebook/autogen_openai_completion.ipynb
  notebook/research/math_level5counting.ipynb
  test/autogen/oai/test_completion.py
  test/autogen/oai/test_notebook.py
  test/autogen/test_agent.py
  test/autogen/test_user_proxy_agent.py
  test/openai/test_notebook.py
  website/blog/2023-05-07-1M-milestone/index.mdx
  website/docs/Examples/AutoGen-OpenAI.md
  website/docs/Use-Cases/Auto-Generation.md
Labels: enhancement

#1048 Blogpost for adaptation in HumanEval
  notebook/research/autogen_code.ipynb
  website/blog/2023-04-21-LLM-tuning-math/index.mdx
  website/blog/2023-05-18-GPT-adaptive-humaneval/img/design.png
  website/blog/2023-05-18-GPT-adaptive-humaneval/img/humaneval.png
  website/blog/2023-05-18-GPT-adaptive-humaneval/index.mdx
  website/docs/Use-Cases/Auto-Generation.md
  website/docs/Use-Cases/Task-Oriented-AutoML.md
Labels: documentation, communication

#1007 create an automl option to remove unnecessary dependency for autogen and tune
  flaml/automl/automl.py
  flaml/automl/data.py
  flaml/automl/ml.py
  flaml/automl/model.py
  flaml/automl/nlp/huggingface/training_args.py
  flaml/automl/nlp/huggingface/utils.py
  flaml/automl/spark/__init__.py
  flaml/automl/spark/metrics.py
  flaml/automl/spark/utils.py
  flaml/automl/state.py
  flaml/automl/task/factory.py
  flaml/automl/task/generic_task.py
  flaml/automl/task/task.py
  flaml/automl/utils.py
  flaml/config.py
  flaml/default/estimator.py
  flaml/default/suggest.py
  flaml/onlineml/trial.py
  flaml/tune/searcher/blendsearch.py
  flaml/tune/spark/utils.py
  flaml/tune/tune.py
  flaml/version.py
  notebook/autogen_chatgpt_gpt4.ipynb
  notebook/autogen_openai_completion.ipynb
  notebook/automl_classification.ipynb
  notebook/automl_lightgbm.ipynb
  notebook/automl_nlp.ipynb
  notebook/automl_synapseML.ipynb
  notebook/automl_time_series_forecast.ipynb
  notebook/automl_xgboost.ipynb
  notebook/integrate_azureml.ipynb
  notebook/integrate_sklearn.ipynb
  notebook/integrate_spark.ipynb
  notebook/research/acl2021.ipynb
  notebook/zeroshot_lightgbm.ipynb
  setup.py
  test/automl/test_utils.py
  website/docs/Examples/AutoGen-OpenAI.md
  website/docs/Examples/AutoML-Classification.md
  website/docs/Examples/AutoML-NLP.md
  website/docs/Examples/AutoML-Rank.md
  website/docs/Examples/AutoML-Regression.md
  website/docs/Examples/AutoML-Time series forecast.md
  website/docs/Examples/AutoML-for-LightGBM.md
  website/docs/Examples/AutoML-for-XGBoost.md
  website/docs/Examples/Default-Flamlized.md
  website/docs/Examples/Integrate - AzureML.md
  website/docs/Examples/Integrate - Scikit-learn Pipeline.md
Labels: dependencies

#1053 doc and test update
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  flaml/autogen/agent/chat_agent.py
  flaml/autogen/agent/user_proxy_agent.py
  test/autogen/test_user_proxy_agent.py
Labels: documentation

#1052 add agent notebook and documentation
  flaml/autogen/agent/agent.py
  flaml/autogen/agent/user_proxy_agent.py
  notebook/autogen_agent_auto_feedback_from_code_execution.ipynb
  website/docs/Use-Cases/Auto-Generation.md
Labels: documentation
