Repository microsoft/FLAML, pull requests merged in 2023-07, with the labels that each got.

#1089 doc update
  flaml/autogen/agent/user_proxy_agent.py
  flaml/autogen/math_utils.py
  notebook/autogen_agent_auto_feedback_from_code_execution.ipynb
  notebook/autogen_agent_human_feedback.ipynb
  notebook/autogen_agent_web_info.ipynb
  test/autogen/test_assistant_agent.py
  website/docs/Use-Cases/Auto-Generation.md
Labels: documentation

#1091 Support function_call in `autogen/agent`
  flaml/autogen/agent/__init__.py
  flaml/autogen/agent/agent.py
  flaml/autogen/agent/assistant_agent.py
  flaml/autogen/agent/math_user_proxy_agent.py
  flaml/autogen/agent/user_proxy_agent.py
  notebook/autogen_agent_auto_feedback_from_code_execution.ipynb
  notebook/autogen_agent_human_feedback.ipynb
  notebook/autogen_agent_web_info.ipynb
  test/autogen/test_agent.py
  test/autogen/test_assistant_agent.py
  test/autogen/test_function_call.py
  website/docs/Use-Cases/Auto-Generation.md
Labels: enhancement

#1112 update notebook with new models
  flaml/autogen/agent/assistant_agent.py
  flaml/autogen/oai/completion.py
  notebook/autogen_agent_auto_feedback_from_code_execution.ipynb
  notebook/autogen_agent_human_feedback.ipynb
  notebook/autogen_agent_planning.ipynb
  notebook/autogen_agent_web_info.ipynb
  website/docs/Use-Cases/Auto-Generation.md
Labels: documentation

#1114 Try to prevent the default AssistantAgent from asking users to modify the code
  flaml/autogen/agent/assistant_agent.py
  flaml/autogen/agent/user_proxy_agent.py
  flaml/autogen/code_utils.py
  notebook/autogen_agent_auto_feedback_from_code_execution.ipynb
  notebook/autogen_agent_human_feedback.ipynb
  notebook/autogen_agent_planning.ipynb
  notebook/autogen_agent_web_info.ipynb
  test/autogen/test_assistant_agent.py
Labels: documentation, enhancement

#1128 Update docs on how to interact with local LLM
  website/blog/2023-07-14-Local-LLMs/index.mdx
  website/blog/authors.yml
  website/docs/Use-Cases/Auto-Generation.md
Labels: documentation

#1133 Json config list, agent refactoring and new notebooks
  .devcontainer/devcontainer.json
  .github/workflows/openai.yml
  flaml/autogen/agent/__init__.py
  flaml/autogen/agent/agent.py
  flaml/autogen/agent/assistant_agent.py
  flaml/autogen/agent/math_user_proxy_agent.py
  flaml/autogen/agent/user_proxy_agent.py
  flaml/autogen/oai/__init__.py
  flaml/autogen/oai/completion.py
  flaml/autogen/oai/openai_utils.py
  notebook/autogen_agent_MathChat.ipynb
  notebook/autogen_agent_auto_feedback_from_code_execution.ipynb
  notebook/autogen_agent_function_call.ipynb
  notebook/autogen_agent_human_feedback.ipynb
  notebook/autogen_agent_planning.ipynb
  notebook/autogen_agent_two_users.ipynb
  notebook/autogen_agent_web_info.ipynb
  notebook/autogen_chatgpt_gpt4.ipynb
  notebook/autogen_openai_completion.ipynb
  notebook/automl_classification.ipynb
  notebook/integrate_spark.ipynb
  test/autogen/oai/test_completion.py
  test/autogen/oai/test_utils.py
  test/autogen/test_agent.py
  test/autogen/test_assistant_agent.py
  test/autogen/test_function_call.py
  test/autogen/test_math_user_proxy_agent.py
  test/autogen/test_user_proxy_agent.py
  test/automl/test_notebook_example.py
  test/automl/test_split.py
  test/automl/test_warmstart.py
  test/spark/test_exceptions.py
  test/spark/test_performance.py
  test/test_autovw.py
  website/blog/2023-07-14-Local-LLMs/index.mdx
  website/docs/Contribute.md
  website/docs/Use-Cases/Auto-Generation.md
Labels: documentation, enhancement
